name: capyflex-env
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - colorama=0.4.6
  - contourpy=1.0.6
  - cycler=0.11.0
  - fonttools=4.38.0
  - freetype=2.12.1
  - jpeg=9e
  - kiwisolver=1.4.4
  - lcms2=2.14
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libdeflate=1.14
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsqlite=3.40.0
  - libtiff=4.4.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libzlib=1.2.13
  - llvm-openmp=15.0.5
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - munkres=1.0.7
  - ncurses=6.3
  - numpy=1.23.5
  - openjpeg=2.5.0
  - openssl=3.0.7
  - packaging=21.3
  - pandas=1.5.2
  - patsy=0.5.3
  - pillow=9.2.0
  - pip=22.3.1
  - pthread-stubs=0.4
  - pyparsing=3.0.9
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2022.6
  - readline=8.1.2
  - scipy=1.9.3
  - seaborn=0.12.1
  - seaborn-base=0.12.1
  - setuptools=65.5.1
  - six=1.16.0
  - sqlite=3.40.0
  - statsmodels=0.13.5
  - tk=8.6.12
  - tomlkit=0.11.6
  - tornado=6.2
  - tqdm=4.64.1
  - typing=3.10.0.0
  - typing_extensions=4.4.0
  - tzdata=2022f
  - unicodedata2=15.0.0
  - wheel=0.38.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - et-xmlfile==1.1.0
    - flowcal==1.3.0
    - imageio==2.22.4
    - joblib==1.2.0
    - networkx==2.8.8
    - openpyxl==3.0.10
    - pywavelets==1.4.1
    - scikit-image==0.19.3
    - scikit-learn==1.1.3
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - xlrd==1.2.0